services:
  - type: web
    name: my-express-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Means this value will be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # Means this value will be set manually in Render dashboard